version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'

  nest:
    build:
      context: .
    container_name: nest-dev
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - '3000:3000'
